update

diff --git a/contestant/bin/hpcm_test b/contestant/bin/hpcm_test
--- a/contestant/bin/hpcm_test
+++ b/contestant/bin/hpcm_test
@@ -4,7 +4,7 @@
 #
 # File:		hpcm_test
 # Author:	Bob Walton (walton@deas.harvard.edu)
-# Date:		Sun May  5 08:07:11 EDT 2013
+# Date:		Sun May 12 15:56:00 EDT 2013
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2013/05/05 13:44:44 $
+#   $Date: 2013/05/12 19:56:40 $
 #   $RCSfile: hpcm_test,v $
-#   $Revision: 1.2 $
+#   $Revision: 1.3 $
 #
 
 allowed_extensions=".c .cc .java .lsp"
@@ -149,6 +149,25 @@ submit() {
 	fi
     fi
 }
+
+if [ "$nomail" == "yes" ]
+then
+    judging_directory=""
+    for j_d in . .. ../.. ../../.. ../../../.. \
+                                   ../../../../../
+    do
+        if [ -r $j_d/hpcm_judging.rc ]
+	then
+	    judging_directory=$j_d
+	    break
+	fi
+    done
+    if [ "$judging_directory" =  "" ]
+    then
+        echo "Cannot find judging directory"
+	exit 1
+    fi
+fi
 
 for name in "$@"
 do
