update

diff --git a/contestant/bin/SETUP_PROTOTYPE b/contestant/bin/SETUP_PROTOTYPE
--- a/contestant/bin/SETUP_PROTOTYPE
+++ b/contestant/bin/SETUP_PROTOTYPE
@@ -4,7 +4,7 @@
 #
 # File:		SETUP_PROTOTYPE
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Mon Oct 29 09:22:08 EST 2001
+# Date:		Sat Mar  9 19:05:57 EST 2002
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,13 +13,13 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: hc3 $
-#   $Date: 2001/10/29 14:21:31 $
+#   $Date: 2002/03/10 00:16:27 $
 #   $RCSfile: SETUP_PROTOTYPE,v $
-#   $Revision: 1.17 $
+#   $Revision: 1.18 $
 
 # List of files always added implicitly to .hpcm_keep
 # and .hpcm_exclude.  Note each line feed is to be
-# followed by a tab.
+# followed by a tab for -doc printing purposes.
 #
 always='home bin .hpcm_contest
 	.hpcm_keep .hpcm_exclude .snapshot'
@@ -93,6 +93,11 @@ SETUP_PROTOTYPE
        JJJ account can log into the PPP account without
        knowing the password of the PPP account.
 
+       If your ssh uses ssh protocol 2 instead of ssh
+       protocol 1, then you may want to use the files
+       authorized_keys2 and id_rsa.pub instead of
+       authorized_keys and identity.pub.
+
     5. In the PPP account edit .cshrc, adding:
 
     	set path=(~/.hpcm_contest/bin \$path)
@@ -122,14 +127,13 @@ SETUP_PROTOTYPE
     set up contestant accounts, and run TRASH_ACCOUNT
     in each contestant account.  This will copy files
     from the prototype account into the contestant
-    account, and will link other files indirectly
-    through the contest directory to copies of the
+    account, and will link other files to copies of the
     files that are now in the ~PPP/home directory.
 
     Prototype ~/home directories are typically shared
     among many different contests, which may also have
     different judging accounts JJJ.  For each contest,
-    the file ~JJJ/contest_foo/home is symbolically
+    the name ~JJJ/contest_foo/home is symbolically
     linked to ~PPP/home, and in each contestant account,
     the file .hcpm_contest is symbolically linked to
     ~JJJ/contest_foo.  Thus for each contestant account,
@@ -160,11 +164,11 @@ SETUP_PROTOTYPE
 
     C2.  If you need to change a file like .procmailrc,
          or .ssh/authorized_keys which has NOT been
-	 moved to ~PPP/home because for security reasons
-	 these files cannot be symbolically linked; or
-	 if you need to add a file or delete a file, you
-	 can do so in the PPP account, but you must then
-	 execute
+	 moved to ~PPP/home (because for security rea-
+	 sons these files cannot be symbolically link-
+	 ed), or if you need to add a file or delete a
+	 file, you can do so in the PPP account, but you
+	 must then execute
 
 	 	SETUP_PROTOTYPE
 
@@ -425,40 +429,6 @@ echo "Files to be tar'ed are:"
 echo "   $files"
 echo ""
 
-# Link ~/.hpcm_contest to `.'.
-#
-rm -f .hpcm_contest
-
-if ln -s . .hpcm_contest
-then
-	echo "linked .hpcm_contest to \`.'"
-else
-	echo "ERROR in ln -s . .hpcm_contest"
-	exit 1
-fi
-
-# Link ~/bin to `dirname $0` if that begins with /
-# but does not begin with `$HOME/'.
-#
-dir=`dirname $0`
-
-case "$dir" in
-    $HOME/*)
-	# Do nothing
-    	;;
-    /*)
-	rm -rf bin
-
-	if ln -s $dir bin
-	then
-		echo "linked bin to $dir"
-	else
-		echo "ERROR in ln -s $dir bin"
-		exit 1
-	fi
-    	;;
-esac
-
 # Create empty.ls.
 #
 rm -f ~/home/empty.ls
@@ -501,5 +471,45 @@ else
 	echo "ERROR in creating ~/home/setup.ls"
 	exit 1
 fi
+
+# Link ~/.hpcm_contest to `.'.
+#
+rm -f .hpcm_contest
+
+if ln -s . .hpcm_contest
+then
+	echo "linked .hpcm_contest to \`.'"
+else
+	echo "ERROR in ln -s . .hpcm_contest"
+	exit 1
+fi
+
+# Link ~/bin to `dirname $0` if that begins with /
+# but does not begin with `$HOME/'.
+#
+dir=`dirname $0`
+
+case "$dir" in
+    $HOME/*)
+	# Do nothing
+    	;;
+    /*)
+	if test -L bin
+	then
+	    rm -rf bin
+	elif test -x bin
+	then
+	    echo "WARNING: bin not a link"
+	fi
+
+	if ln -s $dir bin
+	then
+		echo "linked bin to $dir"
+	else
+		echo "ERROR in ln -s $dir bin"
+		exit 1
+	fi
+    	;;
+esac
 
 exit 0
