update

diff --git a/contestant/bin/SETUP_PROTOTYPE b/contestant/bin/SETUP_PROTOTYPE
--- a/contestant/bin/SETUP_PROTOTYPE
+++ b/contestant/bin/SETUP_PROTOTYPE
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: hc3 $
-#   $Date: 2000/12/07 10:57:17 $
+#   $Date: 2000/12/07 11:01:25 $
 #   $RCSfile: SETUP_PROTOTYPE,v $
-#   $Revision: 1.4 $
+#   $Revision: 1.5 $
 
 # Default list of files and directories that are NOT
 # to be moved to $contest/home.
@@ -303,6 +303,16 @@ do
 		exit 1
 	fi
 done
+
+# Make $contest/home a+rx.
+#
+if chmod a+rx $contest/home
+then
+	echo "chmod a+rx $contest/home"
+else
+	echo "ERROR in chmod a+rx $contest/home"
+	exit 1
+fi
 
 # Link ~/.hpcm_contest to contest directory.
 #
