update

diff --git a/contestant/bin/SETUP_PROTOTYPE b/contestant/bin/SETUP_PROTOTYPE
--- a/contestant/bin/SETUP_PROTOTYPE
+++ b/contestant/bin/SETUP_PROTOTYPE
@@ -4,7 +4,7 @@
 #
 # File:		SETUP_PROTOTYPE
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Fri Oct 16 22:17:40 EDT 2009
+# Date:		Wed Sep 29 07:25:43 EDT 2010
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,32 +13,30 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/10/17 02:18:06 $
+#   $Date: 2010/09/29 13:53:29 $
 #   $RCSfile: SETUP_PROTOTYPE,v $
-#   $Revision: 1.22 $
+#   $Revision: 1.23 $
 
-# List of files always added implicitly to .hpcm_keep
-# and .hpcm_exclude.  Note each line feed is to be
-# followed by a tab for -doc printing purposes.
+# List of files added to `ls -a /etc/skel` that are
+# not in `keep'.
 #
-always='home bin .hpcm_contest .snapshot
-	.hpcm_keep .hpcm_exclude .hpcm_moveonly'
+include="NONE"
 
 # List of files and directories to exclude from tar
-# and that are NOT to be moved to home.
+# and NOT move to home.
 #
-exclude=".Xauthority .history .viminfo"
+exclude="NONE"
 
 # Default list of files and directories that are NOT
 # to be moved to home but are to be included in tar.
 #
-keep=".ssh .procmailrc"
+keep=".ssh .procmailrc .emacs"
 
 # Default list of files and directories that are to
 # be moved to home but not linked from ~ and therefore
 # not included in tar.
 #
-moveonly="RCS"
+move="RCS"
 
 # Process first argument.
 #
@@ -218,21 +216,41 @@ SETUP_PROTOTYPE
     directory of the current (prototype) account.
 
     Then SETUP_PROTOTYPE takes all ordinary files and
-    directories that it finds in ~ (the prototype
-    account home directory) and moves then to the
-    ~/home/ directory.  For every file or directory
-    foo moved, SETUP_PROTOTYPE links ~/foo to .hpcm_
-    contest/home/foo.  There are some exceptions that
-    are NOT moved, which are normally:
+    directories that it finds in etc/skel and moves
+    them to the ~/home/ directory.  For every file or
+    directory foo moved, SETUP_PROTOTYPE links ~/foo
+    to .hpcm_contest/home/foo.  All these links are
+    included in the ~/home/setup.tar file that is used
+    to initialize contestant account home directories.
 
-    	$keep
-	$exclude
-	$always
+    This rule has the following exceptions controlled
+    by the following lists:
 
-    In addition, no link from ~ is made for some of
-    the moved files, which normally are:
+      List     List File      Default
 
-    	$moveonly
+      include  .hpcm_include  $include
+
+      exclude  .hpcm_exclude  $exclude
+
+      keep     .hpcm_keep     $keep
+
+      move     .hpcm_move     $move
+
+    In each case, if the list file exists it is read
+    and the files listed in it become the list.  Other-
+    wise the files listed under \`Default' are the list.
+
+    First, instead of just considering the files in
+    /etc/skel, these files plus those in the include
+    and keep lists minus any files in the exclude
+    list are considered.
+
+    Second, files in the keep list are not moved to
+    ~/home and the files are left untouched in ~.
+
+    Third, files in the move list are moved to ~/home
+    but no link is made in ~ and these files are NOT
+    included in setup.tar.
 
     After moving files and directories, SETUP_PROTOTYPE
     makes the following files in ~/home/:
@@ -252,38 +270,11 @@ SETUP_PROTOTYPE
     reinitialize the home directories of contestant
     accounts.
 
-    By default the following files in ~ are moved to
-    ~/home but are not linked from ~ to ~/home and are
-    not included in setup.tar:
-
-        $moveonly
-
-    This list of files will be changed to the contents
-    of the file ~/.hpcm_moveonly if this file exists.
-
-    By default the following files in ~ are NOT included
-    in setup.tar and not moved to ~/home:
-
-        $exclude
-	$always
-
-    This list of files will be changed to the contents
-    of the file ~/.hpcm_exclude if this file exists,
-    except that the files
-
-    	$always
-
-    are always implicitly added to the contents of
-    ~/.hpcm_exclude.
-
-    By default, the following files in ~ are not moved
-    to ~/home, but if not listed in ~/.hpcm_exclude,
-    will be included in setup.tar:
-
-    	$keep
-
-    This list of files will be changed to the contents
-    of the file ~/.hpcm_keep if this file exists.
+    However, to be more precise, temporary versions
+    of these files are made in empty.ls+, setup.tar+,
+    and setup.ls+, and then only if these are different
+    from any previous versions are they moved into
+    position.
 
     SETUP_PROTOTYPE also manages permissions of ~/home
     and the things it contains.  It sets the permission
@@ -333,18 +324,18 @@ then
 elif mkdir ~/home
 then
 	echo "mkdir ~/home"
+	if chmod 755 ~/home
+	then
+		echo "chmod 755 ~/home"
+	else
+		echo "ERROR in chmod 755 ~/home"
+		exit 1
+	fi
 else
 	echo "ERROR in mkdir ~/home"
 	exit 1
 fi
 
-if chmod 755 ~/home
-then
-	echo "chmod 755 ~/home"
-else
-	echo "ERROR in chmod 755 ~/home"
-	exit 1
-fi
 
 if chmod a+x .
 then
@@ -355,36 +346,37 @@ else
 fi
 
 
-# Read ~/.hpcm_{keep,exclude,moveonly} if they exist.
+# Read ~/.hpcm_{include,exclude,keep,move} if they
+# exist.
 #
-if test -f .hpcm_keep
-then
-	keep=`cat .hpcm_keep`
-fi
-if test -f .hpcm_exclude
-then
-	exclude=`cat .hpcm_exclude`
-fi
-if test -f .hpcm_moveonly
-then
-	moveonly=`cat .hpcm_moveonly`
-fi
+for list in include exclude keep move
+do
+    if test -f .hpcm_$list
+    then
+        $list=`cat .hpcm_$list`
+    fi
+done
 
 # List of files to be tarred:
 #
 files=
 
-# Move everything in the home directory that is not a
-# symbolic link already, except things listed in `keep',
-# `exclude', or `always'.  Add everything to tar list
-# that is not in `exclude' or `always' or `moveonly'.
+# List of files to be linked or kept that do not exist
+# in ~.
 #
-# Just move but do not link anything in `moveonly.
+non_existent=
+
+# Move or keep files or directories listed in /etc/skel,
+# include list, and keep list, unless they are listed in
+# exclude list, or are . or ...   Put these files in the
+# list of files to be tar'ed.  Do not put process any
+# file twice (in case it is listed twice in /etc/skel,
+# include, and keep lists).
 #
-for i in .[^.]* *
+for i in `ls -a /etc/skel` $include $keep
 do
 	found=no
-	for j in $moveonly
+	for j in $exclude $files $non_existent . ..
 	do
 		if test "$i" = "$j"
 		then
@@ -395,35 +387,12 @@ do
 
 	if test $found = yes
 	then
-
-		if test ! -d "$i" -a ! -f "$i"
-		then
-			continue
-		fi
-
-		if mv "$i" ~/home
-		then
-			echo "moved $i to ~/home"
-		else
-			echo ERROR in mv "$i" ~/home
-			exit 1
-		fi
-
 		continue
 	fi
 
-	found=no
-	for j in $exclude $always
-	do
-		if test "$i" = "$j"
-		then
-			found=yes
-			break
-		fi
-	done
-
-	if test $found = yes
+	if test ! -L "$i" -a ! -e "$i"
 	then
+		non_existent="$non_existent $i"
 		continue
 	fi
 
@@ -441,39 +410,49 @@ do
 
 	if test $found = yes
 	then
+		if test -L "$i" -a \
+		        "`readlink "$i"`" \
+			= ".hpcm_contest/home/$i"
+		then
+			echo ERROR: "$i" is supposed \
+			     to be kept but it is \
+			     already
+			echo "      " linked to \
+		             ".hpcm_contest/home/$i"
+			echo "      " perhaps you \
+		             should mv it back to '~'
+			exit 1
+		fi
+
+		continue
+	fi
+
+	if test -L "$i" -a \
+		  "`readlink "$i"`" \
+		= ".hpcm_contest/home/$i"
+	then
 		continue
 	fi
 
 	if test -L "$i"
 	then
-		continue
+		echo ERROR: "$i" is a symbolic link \
+		            but not to \
+			    ".hpcm_contest/home/$i"
+		exit 1
 	fi
 
 	if test ! -d "$i" -a ! -f "$i"
 	then
-		continue
+		echo ERROR: "$i" is NOT a directory or \
+		            ordinary file
+		exit 1
 	fi
 
-        if test -r "$i"
+	if test -L ~/home/"$i" -o -e ~/home/"$i"
 	then
-	    if chmod a+r "$i"
-	    then
-		    echo "chmod a+r $i"
-	    else
-		    echo ERROR in chmod a+r "$i"
-		    exit 1
-	    fi
-	fi
-
-        if test -x "$i"
-	then
-	    if chmod a+x "$i"
-	    then
-		    echo "chmod a+x $i"
-	    else
-		    echo ERROR in chmod a+x "$i"
-		    exit 1
-	    fi
+		echo ERROR: ~/home/"$i" already exists
+		exit 1
 	fi
 
 	if mv "$i" ~/home
@@ -482,6 +461,28 @@ do
 	else
 		echo ERROR in mv "$i" ~/home
 		exit 1
+	fi
+
+        if test -r "~/home/$i"
+	then
+	    if chmod a+r "~/home/$i"
+	    then
+		    echo "chmod a+r ~/home/$i"
+	    else
+		    echo ERROR in chmod a+r "~/home/$i"
+		    exit 1
+	    fi
+	fi
+
+        if test -x "~/home/$i"
+	then
+	    if chmod a+x "~/home/$i"
+	    then
+		    echo "chmod a+x ~/home/$i"
+	    else
+		    echo ERROR in chmod a+x "~/home/$i"
+		    exit 1
+	    fi
 	fi
 
 	if ln -s ".hpcm_contest/home/$i" "$i"
@@ -495,63 +496,144 @@ do
 	fi
 done
 
+# Move the stuff in the move list.
+#
+for i in $move
+do
+
+	if test -L "$i"
+	then
+		echo ERROR: "$i" is a symbolic link
+		exit 1
+	fi
+
+	if test ! -e "$i"
+	then
+		continue
+	fi
+
+	if test ! -d "$i" -a ! -f "$i"
+	then
+		echo ERROR: "$i" is not a directory \
+		            or ordinary file
+		exit 1
+	fi
+
+	if test -L ~/home/"$i" -o -e ~/home/"$i"
+	then
+		echo ERROR: ~/home/"$i" \
+			    already exists
+		exit 1
+	fi
+
+	if mv "$i" ~/home
+	then
+		echo "moved $i to ~/home"
+	else
+		echo ERROR in mv "$i" ~/home
+		exit 1
+	fi
+
+	continue
+done
+
 echo "Files to be tar'ed are:"
 echo "   $files"
 echo ""
 
-# Create empty.ls.
+# Create empty.ls+.
 #
-rm -f ~/home/empty.ls
+rm -f ~/home/empty.ls+
 
-if (echo >~/home/empty.ls "."; \
-    echo >>~/home/empty.ls ".."; \
-    chmod a+r ~/home/empty.ls)
+if (echo >~/home/empty.ls+ "."; \
+    echo >>~/home/empty.ls+ ".."; \
+    chmod a+r ~/home/empty.ls+)
 then
-	echo "created ~/home/empty.ls"
+	do_nothing=
 else
-	echo "ERROR in creating ~/home/empty.ls"
+	echo "ERROR in creating ~/home/empty.ls+"
 	exit 1
 fi
 
-# Create setup.tar.
+# Create setup.tar+.
 #
-rm -f ~/home/setup.tar
-if (tar cf ~/home/setup.tar $files; \
-    chmod a+r ~/home/setup.tar)
+rm -f ~/home/setup.tar+
+if (tar cf ~/home/setup.tar+ $files; \
+    chmod a+r ~/home/setup.tar+)
 then
-	echo "created ~/home/setup.tar"
+	do_nothing=
 else
-	echo "ERROR in creating ~/home/setup.tar"
+	echo "ERROR in creating ~/home/setup.tar+"
 	exit 1
 fi
 
-# Create setup.ls
+# Create setup.ls+
 #
-if ( rm -rf ~/home/setup.ls ~/SETUP_PROTOTYPE.tmp; \
+if ( rm -rf ~/home/setup.ls+ ~/SETUP_PROTOTYPE.tmp; \
      mkdir ~/SETUP_PROTOTYPE.tmp; \
      cd ~/SETUP_PROTOTYPE.tmp; \
-     tar xf ../home/setup.tar; \
-     ls -aR >../home/setup.ls; \
+     tar xf ../home/setup.tar+; \
+     ls -aR >../home/setup.ls+; \
      cd; \
      rm -rf ~/SETUP_PROTOTYPE.tmp; \
-     chmod a+r ~/home/setup.ls )
+     chmod a+r ~/home/setup.ls+ )
 then
-	echo "created ~/home/setup.ls"
+	do_nothing=
 else
-	echo "ERROR in creating ~/home/setup.ls"
+	echo "ERROR in creating ~/home/setup.ls+"
 	exit 1
 fi
+
+for f in empty.ls setup.tar setup.ls
+do
+	if cmp -s ~/home/$f+ ~/home/$f
+	then
+		echo no change in ~/home/$f
+    		rm -f ~/home/$f+
+	else
+		if test -e ~/home/$f-
+		then
+		    echo mv -f ~/home/$f- ~/home/$f--
+		    mv -f ~/home/$f- ~/home/$f--
+		fi
+		if test -e ~/home/$f
+		then
+		    if mv -f ~/home/$f ~/home/$f-
+		    then
+			echo mv ~/home/$f ~/home/$f-
+		    else
+			echo ERROR in mv ~/home/$f \
+			                 ~/home/$f-
+			exit 1
+		    fi
+		fi
+		if mv -f ~/home/$f+ ~/home/$f
+		then
+			echo mv -f ~/home/$f+ ~/home/$f
+		else
+			echo ERROR in mv -f ~/home/$f+ \
+					    ~/home/$f
+			exit 1
+		fi
+	fi
+done
 
 # Link ~/.hpcm_contest to `.'.
 #
-rm -f .hpcm_contest
-
-if ln -s . .hpcm_contest
+if test -L .hpcm_contest -a \
+	   "`readlink .hpcm_contest`" = "."
 then
-	echo "linked .hpcm_contest to \`.'"
+	do_nothing=
 else
-	echo "ERROR in ln -s . .hpcm_contest"
-	exit 1
+    rm -f .hpcm_contest
+
+    if ln -s . .hpcm_contest
+    then
+	    echo "linked .hpcm_contest to \`.'"
+    else
+	    echo "ERROR in ln -s . .hpcm_contest"
+	    exit 1
+    fi
 fi
 
 # Link ~/bin to `dirname $0` if that begins with /
@@ -564,22 +646,37 @@ case "$dir" in
 	# Do nothing
     	;;
     /*)
-	if test -L bin
+	if test -L bin -a "`readlink bin`" = "$dir"
 	then
-	    rm -rf bin
-	elif test -x bin
-	then
-	    echo "WARNING: bin not a link"
-	fi
-
-	if ln -s $dir bin
-	then
-		echo "linked bin to $dir"
+		do_nothing=
 	else
-		echo "ERROR in ln -s $dir bin"
-		exit 1
+		if test -L bin
+		then
+		    rm -f bin
+		fi
+
+		if test -e bin
+		then
+		    echo "ERROR: bin not a link"
+		    exit 1
+		fi
+
+		if ln -s $dir bin
+		then
+			echo "linked bin to $dir"
+		else
+			echo "ERROR in ln -s $dir bin"
+			exit 1
+		fi
 	fi
     	;;
 esac
+
+if test "non_existent" != ""
+then
+	echo WARNING: the following do NOT exist in ~
+	echo "        " and cannot be linked or kept:
+	echo "        " $non_existent
+fi
 
 exit 0
