update

diff --git a/contestant/help/email/sh/hpcm_get b/contestant/help/email/sh/hpcm_get
--- a/contestant/help/email/sh/hpcm_get
+++ b/contestant/help/email/sh/hpcm_get
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: hc3 $
-#   $Date: 2001/09/12 17:16:38 $
+#   $Date: 2001/09/12 17:23:47 $
 #   $RCSfile: hpcm_get
-#   $Revision: 1.6 $
+#   $Revision: 1.7 $
 
 # If this is not bash and bash is available, switch to
 # using bash.  Note that `which bash` may output a
@@ -98,7 +98,8 @@ elif test -r ../../../.HPCM_ADDRESS
 then
     home=../../..
 else
-    echo "ERROR: Could not find .HPCM_ADDRESS file"
+    echo "ERROR: Cannot find .HPCM_ADDRESS file"
+    exit 1
 fi
 
 # Loop through the name arguments, or use `help demos'
