update

diff --git a/judge/bin/printer_client b/judge/bin/printer_client
--- a/judge/bin/printer_client
+++ b/judge/bin/printer_client
@@ -131,12 +131,149 @@ key="$1"
 account="$2"
 printer="$3"
 
-TBD
+READ_TIMEOUT=30
+COPROC_TIMEOUT=30
+COPROC_DIED=0
 
-while read -r
+function get_error() {
+    echo "ERROR:"
+    while read -r <&$out -t $COPROC_TIMEOUT
+    do
+        if [[ "$REPLY" == "%%-HPCM_DONE-%%" ]]
+	then
+	    COPROC_DIED=0
+	    return
+	fi
+	echo "    $REPLY"
+    done
+    COPROC_DIED=1
+}
+
+function get_file() {
+    local base="$1"
+    local ext="$2"
+    local fileout
+    rm -f $base.out
+    exec {fileout}>$base.out
+    echo >&$in get "$base$ext"
+
+    COPROC_DIED=1
+    while read -r <&$out -t $COPROC_TIMEOUT
+    do
+        if [[ "$REPLY" == "%%-HPCM_DONE-%%" ]]
+	then
+	    COPROC_DIED=0
+	    break
+        elif [[ "$REPLY" == "%%-HPCM_ERROR-%%" ]]
+	then
+	    get_error
+	    return
+	fi
+	echo "$REPLY" >&$fileout
+    done
+    exec {fileout}>&-
+    if [[ $COPROC_DIED == 0 ]]
+    then
+	mv -f "$base.out" "$base$ext"
+    fi
+}
+
+function get_sum() {
+    local base="$1"
+    local ext="$2"
+    local sum="MISSING MD5 SUM"
+    echo >&$in sum "$base$ext"
+    COPROC_DIED=1
+    while read -r <&$out -t $COPROC_TIMEOUT
+    do
+        if [[ "$REPLY" == "%%-HPCM_DONE-%%" ]]
+	then
+	    COPROC_DIED=0
+	    break
+        elif [[ "$REPLY" == "%%-HPCM_ERROR-%%" ]]
+	then
+	    get_error
+	    return
+        elif [[ "$sum" != "MISSING MD5 SUM" ]]
+	then
+	    sum="MALFORMED MD5 SUM"
+	else
+	    sum="$REPLY"
+	fi
+    done
+    echo "$sum"
+}
+
+while [ x = x ]
 do
-    case "$REPLY" in
-    esac
+    if [[ "$COPROC_PID" != "" ]]
+    then
+	kill -9 $COPROC_PID >&/dev/null
+	wait $COPROC_PID >&/dev/null
+	echo RESTARTING COPROCESS
+    fi
+    coproc printer_server ../lib
+    out=${COPROC[0]}
+    in=${COPROC[1]}
+    COPROC_DIED=0
+
+    while [ x = x ]
+    do
+        read -r -t $READ_TIMEOUT
+	STATUS=$?
+	echo STATUS $STATUS
+	if [[ $STATUS > 128 ]]
+	then
+	    echo TIMEOUT
+	    continue
+	elif [[ $STATUS != 0 ]]
+	then
+	    exit 0
+	fi
+	case "$REPLY" in
+	get* | sum* | print* | done* | ready* )
+	    
+	    [[ "$REPLY" =~ \
+	             ^(get|sum|print|done|ready) ]]
+	    op=${BASH_REMATCH[1]}
+	    if [[ "$REPLY" =~ \
+		     ^${op}[\ \t]+(.*[^\ \t])[\ \t]*$ ]]
+	    then
+		file="${BASH_REMATCH[1]}"
+		if [[ "$file" =~ ^(.*)(\.[^\ \t.]*)$ ]]
+		then
+		    base="${BASH_REMATCH[1]}"
+		    ext="${BASH_REMATCH[2]}"
+		    if [[ "$ext" != ".done" \
+		          && "$ext" != ".ps" ]]
+		    then
+		        echo "ERROR: $file extension" \
+			     "is not .ps or .done"
+			continue
+		    fi
+		    case $op in
+		    get)
+			get_file $base $ext
+			;;
+		    sum)
+			sum=`get_sum $base $ext`
+			echo SUM IS $sum
+			;;
+		    esac
+		else
+		    echo "ERROR: $file has no extension"
+		fi
+	    else
+	        echo "ERROR: badly formed file name" \
+		     "in $REPLY"
+	    fi
+	    ;;
+	esac
+	if [[ $COPROC_DIED == 1 ]]
+	then
+	    break
+	fi
+    done
 done
 
 exit 0
