update

diff --git a/judge/bin/printer_client b/judge/bin/printer_client
--- a/judge/bin/printer_client
+++ b/judge/bin/printer_client
@@ -4,7 +4,7 @@
 #
 # File:		printer_client
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Sun Oct  9 07:36:30 EDT 2016
+# Date:		Wed Oct 12 02:54:03 EDT 2016
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -63,7 +63,7 @@ printer_client PRIVATE-KEY REMOTE-ACCOUNT [PRINTER]
 		and recently printed (recent .done)
 		files are listed.
 
-	time SECONDS
+	time [SECONDS]
 		Reset the time interval between when
 		printer_client is ready to read the
 		next command and when it executes an
@@ -71,7 +71,13 @@ printer_client PRIVATE-KEY REMOTE-ACCOUNT [PRINTER]
 		time is in seconds, with default of 30
 		seconds.  The value 0 means infinity.
 
-    Other occassionally useful command are:
+		If [SECONDS] is not given, the current
+		time is printed.
+
+    Other occassionally useful command are the follow-
+    ing.  In all these commands, FILE must have exten-
+    sion .ps or .done.
+
 
 	listall	List all the files in the server queue.
 		File names have date and time and are
@@ -110,6 +116,10 @@ printer_client PRIVATE-KEY REMOTE-ACCOUNT [PRINTER]
 		If FILE has the .done extension, just
 		change the extension to .ps in the
 		current and server directories.
+
+	remove FILE
+		Remove the file from local directory and
+		and server.
 
 	debug [on|off]
 		If the debug switch is on, a trace of
@@ -150,6 +160,10 @@ function nop() {
     fi
 }
 
+# Call when %%-HPCM_ERROR-%% has been read.  Reads from
+# server until %%-HPCM_DONE-%% read and and prints error
+# message.
+#
 function get_error() {
     echo "ERROR:"
     while read -r <&$out -t $COPROC_TIMEOUT
@@ -163,6 +177,39 @@ function get_error() {
 	echo "    $REPLY"
     done
     COPROC_DIED=1
+}
+
+# Call to finish server command that has no output.
+# Reads until %%-HPCM_DONE-%% read, looking for
+# %%-HPCM_ERROR-%%, and complaining if any other
+# lines encountered.
+#
+function finish() {
+
+    COPROC_DIED=1
+    superfluous_found=0
+    while read -r <&$out -t $COPROC_TIMEOUT
+    do
+        if [[ "$REPLY" == "%%-HPCM_DONE-%%" ]]
+	then
+	    $DEBUGIN "$REPLY"
+	    COPROC_DIED=0
+	    break
+        elif [[ "$REPLY" == "%%-HPCM_ERROR-%%" ]]
+	then
+	    $DEBUGIN "$REPLY"
+	    get_error
+	    return 1
+	fi
+	if [[ $superfluous_found == 0 ]]
+	then
+	    echo "ERROR:"
+	    echo "    Superfluous output from server:"
+	    superfluous_found=1
+	fi
+	echo "    $REPLY"
+    done
+    return $superfluous_found
 }
 
 function listall() {
@@ -209,6 +256,7 @@ function get_file() {
 	then
 	    $DEBUGIN "$REPLY"
 	    get_error
+	    rm -f "$base.out"
 	    return 1
 	fi
 	echo "$REPLY" >&$fileout
@@ -218,8 +266,68 @@ function get_file() {
     then
 	mv -f "$base.out" "$base$ext"
 	return 0
+    else
+	rm -f "$base.out"
+	return 1
     fi
-    return 1
+}
+
+function get_all() {
+    echo >&$in listall
+    $DEBUGOUT listall
+
+    declare -a files=()
+    declare -i i=0
+    COPROC_DIED=1
+    while read -r <&$out -t $COPROC_TIMEOUT
+    do
+        if [[ "$REPLY" == "%%-HPCM_DONE-%%" ]]
+	then
+	    $DEBUGIN "$REPLY"
+	    COPROC_DIED=0
+	    break
+        elif [[ "$REPLY" == "%%-HPCM_ERROR-%%" ]]
+	then
+	    $DEBUGIN "$REPLY"
+	    get_error
+	    return 1
+	fi
+
+	if [[ "$REPLY" =~ ^(.*)(\.${NWS}*)$ ]]
+	then
+	    base="${BASH_REMATCH[1]}"
+	    ext="${BASH_REMATCH[2]}"
+	    if [[ "$ext" != ".ps" ]]
+	    then
+	        continue
+	    fi
+	    file[$i]="$base"
+	    (( i += 1 ))
+	else
+	    echo "ERROR: badly formed file name" \
+		     "returned by server: $REPLY"
+	fi
+    done
+
+    for base in "${files[@]}"
+    do
+	if [ ! -r "$base.ps" ]
+	then
+	    get_file "$base" .ps
+	    if [[ $? != 0 ]]
+	    then
+		break
+	    fi
+	fi
+	lpr -P"$printer" < "$base.ps"
+	echo >&$in done "$base.ps"
+	finish
+	if [[ $? == 0 ]]
+	then
+	    mv -f "$base.ps" \
+		   "$base.done"
+	fi
+    done
 }
 
 function get_sum() {
@@ -257,7 +365,7 @@ do
     then
 	kill -9 $COPROC_PID >&/dev/null
 	wait $COPROC_PID >&/dev/null
-	echo RESTARTING COPROCESS
+	echo ERROR: coprocess died: restarting
     fi
     coproc printer_server ../lib
     out=${COPROC[0]}
@@ -266,7 +374,12 @@ do
 
     while [ x = x ]
     do
-        read -r -t $READ_TIMEOUT
+	if [[ $READ_TIMEOUT != 0 ]]
+	then
+	    read -r -t $READ_TIMEOUT
+	else
+	    read -r
+	fi
 	STATUS=$?
 	if [[ $STATUS > 128 ]]
 	then
@@ -277,7 +390,28 @@ do
 	    exit 0
 	fi
 	case "$REPLY" in
-	get* | sum* | print* | done* | ready* )
+	listall)
+	    listall
+	    ;;
+	time* )
+	    if [[ "$REPLY" =~ ^time${WS}*$ ]]
+	    then
+	        echo "time interval is $READ_TIMEOUT" \
+		     "seconds"
+	    elif [[ "$REPLY" =~ \
+	            ^time${WS}+([0-9]+)${WS}*$ ]]
+	    then
+	        READ_TIMEOUT=${BASH_REMATCH[1]}
+	    else
+	        echo "ERROR: badly formed time" \
+		     "interval in $REPLY"
+	    fi
+	    ;;
+	get)
+	    get_all
+	    ;;
+	get* | sum* | print* | done* | ready* \
+	     | remove* )
 	    
 	    [[ "$REPLY" =~ \
 	             ^(get|sum|print|done|ready) ]]
@@ -336,6 +470,33 @@ do
 			         Found "(Unreadable)"
 			fi
 			;;
+		    done )
+			echo >&$in done "$base$ext"
+			finish
+			if [[ $? == 0 ]]
+			then
+			    mv -f "$base.ps" \
+			           "$base.done"
+			fi
+			;;
+		    ready )
+			echo >&$in ready "$base$ext"
+			finish
+			if [[ $? == 0 ]]
+			then
+			    mv -f "$base.done" \
+			           "$base.ps"
+			fi
+			;;
+		    remove )
+			echo >&$in remove "$base$ext"
+			finish
+			if [[ $? == 0 ]]
+			then
+			    rm -f "$base.done" \
+			          "$base.ps"
+			fi
+			;;
 		    esac
 		else
 		    echo "ERROR: $file has no extension"
@@ -344,9 +505,6 @@ do
 	        echo "ERROR: badly formed file name" \
 		     "in $REPLY"
 	    fi
-	    ;;
-	listall)
-	    listall
 	    ;;
 	debug*)
 	    if [[ "$REPLY" =~ \
