update

diff --git a/judge/bin/printer_server b/judge/bin/printer_server
--- a/judge/bin/printer_server
+++ b/judge/bin/printer_server
@@ -4,7 +4,7 @@
 #
 # File:		printer_server
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Thu Oct  6 07:31:17 EDT 2016
+# Date:		Thu Oct  6 11:12:57 EDT 2016
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -70,7 +70,8 @@ while read -r
 do
     case "$REPLY" in
     listall )
-        out="`if cd $dir 2>&1; then ls -1; else exit 1; fi`"
+        out="`if cd $dir 2>&1; then ls -1; \
+	                       else exit 1; fi`"
 	if [ $? -ne 0 ]
 	then
 	    echo '%%-HPCM_ERROR-%%'
@@ -89,6 +90,48 @@ do
 	    else
 		echo '%%-HPCM_ERROR-%%'
 		echo Cannot read "$dir/$file"
+	    fi
+	else
+	    echo '%%-HPCM_ERROR-%%'
+	    echo Badly Formed Command: $REPLY
+	fi
+	echo '%%-HPCM_DONE-%%'
+	;;
+    done* | ready* )
+
+	[[ "$REPLY" =~ ^(done|ready) ]]
+	op=${BASH_REMATCH[1]}
+	if [ $op = "done" ]
+	then
+	    src=ps
+	    des=done
+	else
+	    src=done
+	    des=ps
+	fi
+
+        if [[ "$REPLY" =~ \
+	          ^${op}[\ \t]+(.*[^\ \t])[\ \t]*$ ]]
+	then
+	    file="${BASH_REMATCH[1]}"
+	    if [[ "$file" =~ ^(.*)(\.[^\ \t.]*)$ ]]
+	    then
+		base="${BASH_REMATCH[1]}"
+		ext="${BASH_REMATCH[2]}"
+		if [ -e "$dir/${base}.$src" ]
+		then
+		    mv -f "$dir/${base}.$src" \
+		       "$dir/${base}.$des"
+		elif [ ! -e "$dir/${base}.$des" ]
+		then
+		    echo '%%-HPCM_ERROR-%%'
+		    echo "${base}.{ps,done}" does \
+		         not exist
+		fi
+	    else
+		echo '%%-HPCM_ERROR-%%'
+		echo "$file" does not have \
+		     extension
 	    fi
 	else
 	    echo '%%-HPCM_ERROR-%%'
